




<Main_box>:
    orientation: 'vertical'
    size_hint_y: None
    height:2000
    spacing: 30
    pos_hint: {'center_x' : 0.5,'center_y' : 0.5}

    


    
    

<Marks_box>:
    orientation:'vertical'
    spacing: 30
    md_bg_color: 0, 1, 1, 1
<Horizontal_b>:
    orientation:'horizontal'


<Mark_label>:
    theme_text_color: "Custom"
    text_color: 0, 0, 0, 1
    size: self.texture_size
    
    


